//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: CryptoService.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import Dispatch
import SwiftGRPC
import SwiftProtobuf

internal protocol Proto_CryptoServicecreateAccountCall: ClientCallUnary {}

fileprivate final class Proto_CryptoServicecreateAccountCallBase: ClientCallUnaryBase<Proto_Transaction, Proto_TransactionResponse>, Proto_CryptoServicecreateAccountCall {
  override class var method: String { return "/proto.CryptoService/createAccount" }
}

internal protocol Proto_CryptoServiceupdateAccountCall: ClientCallUnary {}

fileprivate final class Proto_CryptoServiceupdateAccountCallBase: ClientCallUnaryBase<Proto_Transaction, Proto_TransactionResponse>, Proto_CryptoServiceupdateAccountCall {
  override class var method: String { return "/proto.CryptoService/updateAccount" }
}

internal protocol Proto_CryptoServicecryptoTransferCall: ClientCallUnary {}

fileprivate final class Proto_CryptoServicecryptoTransferCallBase: ClientCallUnaryBase<Proto_Transaction, Proto_TransactionResponse>, Proto_CryptoServicecryptoTransferCall {
  override class var method: String { return "/proto.CryptoService/cryptoTransfer" }
}

internal protocol Proto_CryptoServicecryptoDeleteCall: ClientCallUnary {}

fileprivate final class Proto_CryptoServicecryptoDeleteCallBase: ClientCallUnaryBase<Proto_Transaction, Proto_TransactionResponse>, Proto_CryptoServicecryptoDeleteCall {
  override class var method: String { return "/proto.CryptoService/cryptoDelete" }
}

internal protocol Proto_CryptoServiceaddClaimCall: ClientCallUnary {}

fileprivate final class Proto_CryptoServiceaddClaimCallBase: ClientCallUnaryBase<Proto_Transaction, Proto_TransactionResponse>, Proto_CryptoServiceaddClaimCall {
  override class var method: String { return "/proto.CryptoService/addClaim" }
}

internal protocol Proto_CryptoServicedeleteClaimCall: ClientCallUnary {}

fileprivate final class Proto_CryptoServicedeleteClaimCallBase: ClientCallUnaryBase<Proto_Transaction, Proto_TransactionResponse>, Proto_CryptoServicedeleteClaimCall {
  override class var method: String { return "/proto.CryptoService/deleteClaim" }
}

internal protocol Proto_CryptoServicegetClaimCall: ClientCallUnary {}

fileprivate final class Proto_CryptoServicegetClaimCallBase: ClientCallUnaryBase<Proto_Query, Proto_Response>, Proto_CryptoServicegetClaimCall {
  override class var method: String { return "/proto.CryptoService/getClaim" }
}

internal protocol Proto_CryptoServicegetAccountRecordsCall: ClientCallUnary {}

fileprivate final class Proto_CryptoServicegetAccountRecordsCallBase: ClientCallUnaryBase<Proto_Query, Proto_Response>, Proto_CryptoServicegetAccountRecordsCall {
  override class var method: String { return "/proto.CryptoService/getAccountRecords" }
}

internal protocol Proto_CryptoServicecryptoGetBalanceCall: ClientCallUnary {}

fileprivate final class Proto_CryptoServicecryptoGetBalanceCallBase: ClientCallUnaryBase<Proto_Query, Proto_Response>, Proto_CryptoServicecryptoGetBalanceCall {
  override class var method: String { return "/proto.CryptoService/cryptoGetBalance" }
}

internal protocol Proto_CryptoServicegetAccountInfoCall: ClientCallUnary {}

fileprivate final class Proto_CryptoServicegetAccountInfoCallBase: ClientCallUnaryBase<Proto_Query, Proto_Response>, Proto_CryptoServicegetAccountInfoCall {
  override class var method: String { return "/proto.CryptoService/getAccountInfo" }
}

internal protocol Proto_CryptoServicegetTransactionReceiptsCall: ClientCallUnary {}

fileprivate final class Proto_CryptoServicegetTransactionReceiptsCallBase: ClientCallUnaryBase<Proto_Query, Proto_Response>, Proto_CryptoServicegetTransactionReceiptsCall {
  override class var method: String { return "/proto.CryptoService/getTransactionReceipts" }
}

internal protocol Proto_CryptoServicegetTxRecordByTxIDCall: ClientCallUnary {}

fileprivate final class Proto_CryptoServicegetTxRecordByTxIDCallBase: ClientCallUnaryBase<Proto_Query, Proto_Response>, Proto_CryptoServicegetTxRecordByTxIDCall {
  override class var method: String { return "/proto.CryptoService/getTxRecordByTxID" }
}

internal protocol Proto_CryptoServicegetStakersByAccountIDCall: ClientCallUnary {}

fileprivate final class Proto_CryptoServicegetStakersByAccountIDCallBase: ClientCallUnaryBase<Proto_Query, Proto_Response>, Proto_CryptoServicegetStakersByAccountIDCall {
  override class var method: String { return "/proto.CryptoService/getStakersByAccountID" }
}


/// Instantiate Proto_CryptoServiceServiceClient, then call methods of this protocol to make API calls.
internal protocol Proto_CryptoServiceService: ServiceClient {
  /// Synchronous. Unary.
  func createAccount(_ request: Proto_Transaction) throws -> Proto_TransactionResponse
  /// Asynchronous. Unary.
  func createAccount(_ request: Proto_Transaction, completion: @escaping (Proto_TransactionResponse?, CallResult) -> Void) throws -> Proto_CryptoServicecreateAccountCall

  /// Synchronous. Unary.
  func updateAccount(_ request: Proto_Transaction) throws -> Proto_TransactionResponse
  /// Asynchronous. Unary.
  func updateAccount(_ request: Proto_Transaction, completion: @escaping (Proto_TransactionResponse?, CallResult) -> Void) throws -> Proto_CryptoServiceupdateAccountCall

  /// Synchronous. Unary.
  func cryptoTransfer(_ request: Proto_Transaction) throws -> Proto_TransactionResponse
  /// Asynchronous. Unary.
  func cryptoTransfer(_ request: Proto_Transaction, completion: @escaping (Proto_TransactionResponse?, CallResult) -> Void) throws -> Proto_CryptoServicecryptoTransferCall

  /// Synchronous. Unary.
  func cryptoDelete(_ request: Proto_Transaction) throws -> Proto_TransactionResponse
  /// Asynchronous. Unary.
  func cryptoDelete(_ request: Proto_Transaction, completion: @escaping (Proto_TransactionResponse?, CallResult) -> Void) throws -> Proto_CryptoServicecryptoDeleteCall

  /// Synchronous. Unary.
  func addClaim(_ request: Proto_Transaction) throws -> Proto_TransactionResponse
  /// Asynchronous. Unary.
  func addClaim(_ request: Proto_Transaction, completion: @escaping (Proto_TransactionResponse?, CallResult) -> Void) throws -> Proto_CryptoServiceaddClaimCall

  /// Synchronous. Unary.
  func deleteClaim(_ request: Proto_Transaction) throws -> Proto_TransactionResponse
  /// Asynchronous. Unary.
  func deleteClaim(_ request: Proto_Transaction, completion: @escaping (Proto_TransactionResponse?, CallResult) -> Void) throws -> Proto_CryptoServicedeleteClaimCall

  /// Synchronous. Unary.
  func getClaim(_ request: Proto_Query) throws -> Proto_Response
  /// Asynchronous. Unary.
  func getClaim(_ request: Proto_Query, completion: @escaping (Proto_Response?, CallResult) -> Void) throws -> Proto_CryptoServicegetClaimCall

  /// Synchronous. Unary.
  func getAccountRecords(_ request: Proto_Query) throws -> Proto_Response
  /// Asynchronous. Unary.
  func getAccountRecords(_ request: Proto_Query, completion: @escaping (Proto_Response?, CallResult) -> Void) throws -> Proto_CryptoServicegetAccountRecordsCall

  /// Synchronous. Unary.
  func cryptoGetBalance(_ request: Proto_Query) throws -> Proto_Response
  /// Asynchronous. Unary.
  func cryptoGetBalance(_ request: Proto_Query, completion: @escaping (Proto_Response?, CallResult) -> Void) throws -> Proto_CryptoServicecryptoGetBalanceCall

  /// Synchronous. Unary.
  func getAccountInfo(_ request: Proto_Query) throws -> Proto_Response
  /// Asynchronous. Unary.
  func getAccountInfo(_ request: Proto_Query, completion: @escaping (Proto_Response?, CallResult) -> Void) throws -> Proto_CryptoServicegetAccountInfoCall

  /// Synchronous. Unary.
  func getTransactionReceipts(_ request: Proto_Query) throws -> Proto_Response
  /// Asynchronous. Unary.
  func getTransactionReceipts(_ request: Proto_Query, completion: @escaping (Proto_Response?, CallResult) -> Void) throws -> Proto_CryptoServicegetTransactionReceiptsCall

  /// Synchronous. Unary.
  func getTxRecordByTxID(_ request: Proto_Query) throws -> Proto_Response
  /// Asynchronous. Unary.
  func getTxRecordByTxID(_ request: Proto_Query, completion: @escaping (Proto_Response?, CallResult) -> Void) throws -> Proto_CryptoServicegetTxRecordByTxIDCall

  /// Synchronous. Unary.
  func getStakersByAccountID(_ request: Proto_Query) throws -> Proto_Response
  /// Asynchronous. Unary.
  func getStakersByAccountID(_ request: Proto_Query, completion: @escaping (Proto_Response?, CallResult) -> Void) throws -> Proto_CryptoServicegetStakersByAccountIDCall

}

internal final class Proto_CryptoServiceServiceClient: ServiceClientBase, Proto_CryptoServiceService {
  /// Synchronous. Unary.
  internal func createAccount(_ request: Proto_Transaction) throws -> Proto_TransactionResponse {
    return try Proto_CryptoServicecreateAccountCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func createAccount(_ request: Proto_Transaction, completion: @escaping (Proto_TransactionResponse?, CallResult) -> Void) throws -> Proto_CryptoServicecreateAccountCall {
    return try Proto_CryptoServicecreateAccountCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func updateAccount(_ request: Proto_Transaction) throws -> Proto_TransactionResponse {
    return try Proto_CryptoServiceupdateAccountCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func updateAccount(_ request: Proto_Transaction, completion: @escaping (Proto_TransactionResponse?, CallResult) -> Void) throws -> Proto_CryptoServiceupdateAccountCall {
    return try Proto_CryptoServiceupdateAccountCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func cryptoTransfer(_ request: Proto_Transaction) throws -> Proto_TransactionResponse {
    return try Proto_CryptoServicecryptoTransferCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func cryptoTransfer(_ request: Proto_Transaction, completion: @escaping (Proto_TransactionResponse?, CallResult) -> Void) throws -> Proto_CryptoServicecryptoTransferCall {
    return try Proto_CryptoServicecryptoTransferCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func cryptoDelete(_ request: Proto_Transaction) throws -> Proto_TransactionResponse {
    return try Proto_CryptoServicecryptoDeleteCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func cryptoDelete(_ request: Proto_Transaction, completion: @escaping (Proto_TransactionResponse?, CallResult) -> Void) throws -> Proto_CryptoServicecryptoDeleteCall {
    return try Proto_CryptoServicecryptoDeleteCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func addClaim(_ request: Proto_Transaction) throws -> Proto_TransactionResponse {
    return try Proto_CryptoServiceaddClaimCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func addClaim(_ request: Proto_Transaction, completion: @escaping (Proto_TransactionResponse?, CallResult) -> Void) throws -> Proto_CryptoServiceaddClaimCall {
    return try Proto_CryptoServiceaddClaimCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func deleteClaim(_ request: Proto_Transaction) throws -> Proto_TransactionResponse {
    return try Proto_CryptoServicedeleteClaimCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func deleteClaim(_ request: Proto_Transaction, completion: @escaping (Proto_TransactionResponse?, CallResult) -> Void) throws -> Proto_CryptoServicedeleteClaimCall {
    return try Proto_CryptoServicedeleteClaimCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func getClaim(_ request: Proto_Query) throws -> Proto_Response {
    return try Proto_CryptoServicegetClaimCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func getClaim(_ request: Proto_Query, completion: @escaping (Proto_Response?, CallResult) -> Void) throws -> Proto_CryptoServicegetClaimCall {
    return try Proto_CryptoServicegetClaimCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func getAccountRecords(_ request: Proto_Query) throws -> Proto_Response {
    return try Proto_CryptoServicegetAccountRecordsCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func getAccountRecords(_ request: Proto_Query, completion: @escaping (Proto_Response?, CallResult) -> Void) throws -> Proto_CryptoServicegetAccountRecordsCall {
    return try Proto_CryptoServicegetAccountRecordsCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func cryptoGetBalance(_ request: Proto_Query) throws -> Proto_Response {
    return try Proto_CryptoServicecryptoGetBalanceCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func cryptoGetBalance(_ request: Proto_Query, completion: @escaping (Proto_Response?, CallResult) -> Void) throws -> Proto_CryptoServicecryptoGetBalanceCall {
    return try Proto_CryptoServicecryptoGetBalanceCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func getAccountInfo(_ request: Proto_Query) throws -> Proto_Response {
    return try Proto_CryptoServicegetAccountInfoCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func getAccountInfo(_ request: Proto_Query, completion: @escaping (Proto_Response?, CallResult) -> Void) throws -> Proto_CryptoServicegetAccountInfoCall {
    return try Proto_CryptoServicegetAccountInfoCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func getTransactionReceipts(_ request: Proto_Query) throws -> Proto_Response {
    return try Proto_CryptoServicegetTransactionReceiptsCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func getTransactionReceipts(_ request: Proto_Query, completion: @escaping (Proto_Response?, CallResult) -> Void) throws -> Proto_CryptoServicegetTransactionReceiptsCall {
    return try Proto_CryptoServicegetTransactionReceiptsCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func getTxRecordByTxID(_ request: Proto_Query) throws -> Proto_Response {
    return try Proto_CryptoServicegetTxRecordByTxIDCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func getTxRecordByTxID(_ request: Proto_Query, completion: @escaping (Proto_Response?, CallResult) -> Void) throws -> Proto_CryptoServicegetTxRecordByTxIDCall {
    return try Proto_CryptoServicegetTxRecordByTxIDCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func getStakersByAccountID(_ request: Proto_Query) throws -> Proto_Response {
    return try Proto_CryptoServicegetStakersByAccountIDCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func getStakersByAccountID(_ request: Proto_Query, completion: @escaping (Proto_Response?, CallResult) -> Void) throws -> Proto_CryptoServicegetStakersByAccountIDCall {
    return try Proto_CryptoServicegetStakersByAccountIDCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Proto_CryptoServiceProvider {
  func createAccount(request: Proto_Transaction, session: Proto_CryptoServicecreateAccountSession) throws -> Proto_TransactionResponse
  func updateAccount(request: Proto_Transaction, session: Proto_CryptoServiceupdateAccountSession) throws -> Proto_TransactionResponse
  func cryptoTransfer(request: Proto_Transaction, session: Proto_CryptoServicecryptoTransferSession) throws -> Proto_TransactionResponse
  func cryptoDelete(request: Proto_Transaction, session: Proto_CryptoServicecryptoDeleteSession) throws -> Proto_TransactionResponse
  func addClaim(request: Proto_Transaction, session: Proto_CryptoServiceaddClaimSession) throws -> Proto_TransactionResponse
  func deleteClaim(request: Proto_Transaction, session: Proto_CryptoServicedeleteClaimSession) throws -> Proto_TransactionResponse
  func getClaim(request: Proto_Query, session: Proto_CryptoServicegetClaimSession) throws -> Proto_Response
  func getAccountRecords(request: Proto_Query, session: Proto_CryptoServicegetAccountRecordsSession) throws -> Proto_Response
  func cryptoGetBalance(request: Proto_Query, session: Proto_CryptoServicecryptoGetBalanceSession) throws -> Proto_Response
  func getAccountInfo(request: Proto_Query, session: Proto_CryptoServicegetAccountInfoSession) throws -> Proto_Response
  func getTransactionReceipts(request: Proto_Query, session: Proto_CryptoServicegetTransactionReceiptsSession) throws -> Proto_Response
  func getTxRecordByTxID(request: Proto_Query, session: Proto_CryptoServicegetTxRecordByTxIDSession) throws -> Proto_Response
  func getStakersByAccountID(request: Proto_Query, session: Proto_CryptoServicegetStakersByAccountIDSession) throws -> Proto_Response
}

internal protocol Proto_CryptoServicecreateAccountSession: ServerSessionUnary {}

fileprivate final class Proto_CryptoServicecreateAccountSessionBase: ServerSessionUnaryBase<Proto_Transaction, Proto_TransactionResponse>, Proto_CryptoServicecreateAccountSession {}

internal protocol Proto_CryptoServiceupdateAccountSession: ServerSessionUnary {}

fileprivate final class Proto_CryptoServiceupdateAccountSessionBase: ServerSessionUnaryBase<Proto_Transaction, Proto_TransactionResponse>, Proto_CryptoServiceupdateAccountSession {}

internal protocol Proto_CryptoServicecryptoTransferSession: ServerSessionUnary {}

fileprivate final class Proto_CryptoServicecryptoTransferSessionBase: ServerSessionUnaryBase<Proto_Transaction, Proto_TransactionResponse>, Proto_CryptoServicecryptoTransferSession {}

internal protocol Proto_CryptoServicecryptoDeleteSession: ServerSessionUnary {}

fileprivate final class Proto_CryptoServicecryptoDeleteSessionBase: ServerSessionUnaryBase<Proto_Transaction, Proto_TransactionResponse>, Proto_CryptoServicecryptoDeleteSession {}

internal protocol Proto_CryptoServiceaddClaimSession: ServerSessionUnary {}

fileprivate final class Proto_CryptoServiceaddClaimSessionBase: ServerSessionUnaryBase<Proto_Transaction, Proto_TransactionResponse>, Proto_CryptoServiceaddClaimSession {}

internal protocol Proto_CryptoServicedeleteClaimSession: ServerSessionUnary {}

fileprivate final class Proto_CryptoServicedeleteClaimSessionBase: ServerSessionUnaryBase<Proto_Transaction, Proto_TransactionResponse>, Proto_CryptoServicedeleteClaimSession {}

internal protocol Proto_CryptoServicegetClaimSession: ServerSessionUnary {}

fileprivate final class Proto_CryptoServicegetClaimSessionBase: ServerSessionUnaryBase<Proto_Query, Proto_Response>, Proto_CryptoServicegetClaimSession {}

internal protocol Proto_CryptoServicegetAccountRecordsSession: ServerSessionUnary {}

fileprivate final class Proto_CryptoServicegetAccountRecordsSessionBase: ServerSessionUnaryBase<Proto_Query, Proto_Response>, Proto_CryptoServicegetAccountRecordsSession {}

internal protocol Proto_CryptoServicecryptoGetBalanceSession: ServerSessionUnary {}

fileprivate final class Proto_CryptoServicecryptoGetBalanceSessionBase: ServerSessionUnaryBase<Proto_Query, Proto_Response>, Proto_CryptoServicecryptoGetBalanceSession {}

internal protocol Proto_CryptoServicegetAccountInfoSession: ServerSessionUnary {}

fileprivate final class Proto_CryptoServicegetAccountInfoSessionBase: ServerSessionUnaryBase<Proto_Query, Proto_Response>, Proto_CryptoServicegetAccountInfoSession {}

internal protocol Proto_CryptoServicegetTransactionReceiptsSession: ServerSessionUnary {}

fileprivate final class Proto_CryptoServicegetTransactionReceiptsSessionBase: ServerSessionUnaryBase<Proto_Query, Proto_Response>, Proto_CryptoServicegetTransactionReceiptsSession {}

internal protocol Proto_CryptoServicegetTxRecordByTxIDSession: ServerSessionUnary {}

fileprivate final class Proto_CryptoServicegetTxRecordByTxIDSessionBase: ServerSessionUnaryBase<Proto_Query, Proto_Response>, Proto_CryptoServicegetTxRecordByTxIDSession {}

internal protocol Proto_CryptoServicegetStakersByAccountIDSession: ServerSessionUnary {}

fileprivate final class Proto_CryptoServicegetStakersByAccountIDSessionBase: ServerSessionUnaryBase<Proto_Query, Proto_Response>, Proto_CryptoServicegetStakersByAccountIDSession {}


/// Main server for generated service
internal final class Proto_CryptoServiceServer: ServiceServer {
  private let provider: Proto_CryptoServiceProvider

  internal init(address: String, provider: Proto_CryptoServiceProvider) {
    self.provider = provider
    super.init(address: address)
  }

  internal init?(address: String, certificateURL: URL, keyURL: URL, provider: Proto_CryptoServiceProvider) {
    self.provider = provider
    super.init(address: address, certificateURL: certificateURL, keyURL: keyURL)
  }

  internal init?(address: String, certificateString: String, keyString: String, provider: Proto_CryptoServiceProvider) {
    self.provider = provider
    super.init(address: address, certificateString: certificateString, keyString: keyString)
  }

  /// Start the server.
  internal override func handleMethod(_ method: String, handler: Handler, queue: DispatchQueue) throws -> Bool {
    let provider = self.provider
    switch method {
    case "/proto.CryptoService/createAccount":
      try Proto_CryptoServicecreateAccountSessionBase(
        handler: handler,
        providerBlock: { try provider.createAccount(request: $0, session: $1 as! Proto_CryptoServicecreateAccountSessionBase) })
          .run(queue: queue)
      return true
    case "/proto.CryptoService/updateAccount":
      try Proto_CryptoServiceupdateAccountSessionBase(
        handler: handler,
        providerBlock: { try provider.updateAccount(request: $0, session: $1 as! Proto_CryptoServiceupdateAccountSessionBase) })
          .run(queue: queue)
      return true
    case "/proto.CryptoService/cryptoTransfer":
      try Proto_CryptoServicecryptoTransferSessionBase(
        handler: handler,
        providerBlock: { try provider.cryptoTransfer(request: $0, session: $1 as! Proto_CryptoServicecryptoTransferSessionBase) })
          .run(queue: queue)
      return true
    case "/proto.CryptoService/cryptoDelete":
      try Proto_CryptoServicecryptoDeleteSessionBase(
        handler: handler,
        providerBlock: { try provider.cryptoDelete(request: $0, session: $1 as! Proto_CryptoServicecryptoDeleteSessionBase) })
          .run(queue: queue)
      return true
    case "/proto.CryptoService/addClaim":
      try Proto_CryptoServiceaddClaimSessionBase(
        handler: handler,
        providerBlock: { try provider.addClaim(request: $0, session: $1 as! Proto_CryptoServiceaddClaimSessionBase) })
          .run(queue: queue)
      return true
    case "/proto.CryptoService/deleteClaim":
      try Proto_CryptoServicedeleteClaimSessionBase(
        handler: handler,
        providerBlock: { try provider.deleteClaim(request: $0, session: $1 as! Proto_CryptoServicedeleteClaimSessionBase) })
          .run(queue: queue)
      return true
    case "/proto.CryptoService/getClaim":
      try Proto_CryptoServicegetClaimSessionBase(
        handler: handler,
        providerBlock: { try provider.getClaim(request: $0, session: $1 as! Proto_CryptoServicegetClaimSessionBase) })
          .run(queue: queue)
      return true
    case "/proto.CryptoService/getAccountRecords":
      try Proto_CryptoServicegetAccountRecordsSessionBase(
        handler: handler,
        providerBlock: { try provider.getAccountRecords(request: $0, session: $1 as! Proto_CryptoServicegetAccountRecordsSessionBase) })
          .run(queue: queue)
      return true
    case "/proto.CryptoService/cryptoGetBalance":
      try Proto_CryptoServicecryptoGetBalanceSessionBase(
        handler: handler,
        providerBlock: { try provider.cryptoGetBalance(request: $0, session: $1 as! Proto_CryptoServicecryptoGetBalanceSessionBase) })
          .run(queue: queue)
      return true
    case "/proto.CryptoService/getAccountInfo":
      try Proto_CryptoServicegetAccountInfoSessionBase(
        handler: handler,
        providerBlock: { try provider.getAccountInfo(request: $0, session: $1 as! Proto_CryptoServicegetAccountInfoSessionBase) })
          .run(queue: queue)
      return true
    case "/proto.CryptoService/getTransactionReceipts":
      try Proto_CryptoServicegetTransactionReceiptsSessionBase(
        handler: handler,
        providerBlock: { try provider.getTransactionReceipts(request: $0, session: $1 as! Proto_CryptoServicegetTransactionReceiptsSessionBase) })
          .run(queue: queue)
      return true
    case "/proto.CryptoService/getTxRecordByTxID":
      try Proto_CryptoServicegetTxRecordByTxIDSessionBase(
        handler: handler,
        providerBlock: { try provider.getTxRecordByTxID(request: $0, session: $1 as! Proto_CryptoServicegetTxRecordByTxIDSessionBase) })
          .run(queue: queue)
      return true
    case "/proto.CryptoService/getStakersByAccountID":
      try Proto_CryptoServicegetStakersByAccountIDSessionBase(
        handler: handler,
        providerBlock: { try provider.getStakersByAccountID(request: $0, session: $1 as! Proto_CryptoServicegetStakersByAccountIDSessionBase) })
          .run(queue: queue)
      return true
    default:
      return false
    }
  }
}

