//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: SmartContractService.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import Dispatch
import SwiftGRPC
import SwiftProtobuf

internal protocol Proto_SmartContractServicecreateContractCall: ClientCallUnary {}

fileprivate final class Proto_SmartContractServicecreateContractCallBase: ClientCallUnaryBase<Proto_Transaction, Proto_TransactionResponse>, Proto_SmartContractServicecreateContractCall {
  override class var method: String { return "/proto.SmartContractService/createContract" }
}

internal protocol Proto_SmartContractServiceupdateContractCall: ClientCallUnary {}

fileprivate final class Proto_SmartContractServiceupdateContractCallBase: ClientCallUnaryBase<Proto_Transaction, Proto_TransactionResponse>, Proto_SmartContractServiceupdateContractCall {
  override class var method: String { return "/proto.SmartContractService/updateContract" }
}

internal protocol Proto_SmartContractServicecontractCallMethodCall: ClientCallUnary {}

fileprivate final class Proto_SmartContractServicecontractCallMethodCallBase: ClientCallUnaryBase<Proto_Transaction, Proto_TransactionResponse>, Proto_SmartContractServicecontractCallMethodCall {
  override class var method: String { return "/proto.SmartContractService/contractCallMethod" }
}

internal protocol Proto_SmartContractServicegetContractInfoCall: ClientCallUnary {}

fileprivate final class Proto_SmartContractServicegetContractInfoCallBase: ClientCallUnaryBase<Proto_Query, Proto_Response>, Proto_SmartContractServicegetContractInfoCall {
  override class var method: String { return "/proto.SmartContractService/getContractInfo" }
}

internal protocol Proto_SmartContractServicecontractCallLocalMethodCall: ClientCallUnary {}

fileprivate final class Proto_SmartContractServicecontractCallLocalMethodCallBase: ClientCallUnaryBase<Proto_Query, Proto_Response>, Proto_SmartContractServicecontractCallLocalMethodCall {
  override class var method: String { return "/proto.SmartContractService/contractCallLocalMethod" }
}

internal protocol Proto_SmartContractServiceContractGetBytecodeCall: ClientCallUnary {}

fileprivate final class Proto_SmartContractServiceContractGetBytecodeCallBase: ClientCallUnaryBase<Proto_Query, Proto_Response>, Proto_SmartContractServiceContractGetBytecodeCall {
  override class var method: String { return "/proto.SmartContractService/ContractGetBytecode" }
}

internal protocol Proto_SmartContractServicegetBySolidityIDCall: ClientCallUnary {}

fileprivate final class Proto_SmartContractServicegetBySolidityIDCallBase: ClientCallUnaryBase<Proto_Query, Proto_Response>, Proto_SmartContractServicegetBySolidityIDCall {
  override class var method: String { return "/proto.SmartContractService/getBySolidityID" }
}

internal protocol Proto_SmartContractServicegetTxRecordByContractIDCall: ClientCallUnary {}

fileprivate final class Proto_SmartContractServicegetTxRecordByContractIDCallBase: ClientCallUnaryBase<Proto_Query, Proto_Response>, Proto_SmartContractServicegetTxRecordByContractIDCall {
  override class var method: String { return "/proto.SmartContractService/getTxRecordByContractID" }
}


/// Instantiate Proto_SmartContractServiceServiceClient, then call methods of this protocol to make API calls.
internal protocol Proto_SmartContractServiceService: ServiceClient {
  /// Synchronous. Unary.
  func createContract(_ request: Proto_Transaction) throws -> Proto_TransactionResponse
  /// Asynchronous. Unary.
  func createContract(_ request: Proto_Transaction, completion: @escaping (Proto_TransactionResponse?, CallResult) -> Void) throws -> Proto_SmartContractServicecreateContractCall

  /// Synchronous. Unary.
  func updateContract(_ request: Proto_Transaction) throws -> Proto_TransactionResponse
  /// Asynchronous. Unary.
  func updateContract(_ request: Proto_Transaction, completion: @escaping (Proto_TransactionResponse?, CallResult) -> Void) throws -> Proto_SmartContractServiceupdateContractCall

  /// Synchronous. Unary.
  func contractCallMethod(_ request: Proto_Transaction) throws -> Proto_TransactionResponse
  /// Asynchronous. Unary.
  func contractCallMethod(_ request: Proto_Transaction, completion: @escaping (Proto_TransactionResponse?, CallResult) -> Void) throws -> Proto_SmartContractServicecontractCallMethodCall

  /// Synchronous. Unary.
  func getContractInfo(_ request: Proto_Query) throws -> Proto_Response
  /// Asynchronous. Unary.
  func getContractInfo(_ request: Proto_Query, completion: @escaping (Proto_Response?, CallResult) -> Void) throws -> Proto_SmartContractServicegetContractInfoCall

  /// Synchronous. Unary.
  func contractCallLocalMethod(_ request: Proto_Query) throws -> Proto_Response
  /// Asynchronous. Unary.
  func contractCallLocalMethod(_ request: Proto_Query, completion: @escaping (Proto_Response?, CallResult) -> Void) throws -> Proto_SmartContractServicecontractCallLocalMethodCall

  /// Synchronous. Unary.
  func contractGetBytecode(_ request: Proto_Query) throws -> Proto_Response
  /// Asynchronous. Unary.
  func contractGetBytecode(_ request: Proto_Query, completion: @escaping (Proto_Response?, CallResult) -> Void) throws -> Proto_SmartContractServiceContractGetBytecodeCall

  /// Synchronous. Unary.
  func getBySolidityID(_ request: Proto_Query) throws -> Proto_Response
  /// Asynchronous. Unary.
  func getBySolidityID(_ request: Proto_Query, completion: @escaping (Proto_Response?, CallResult) -> Void) throws -> Proto_SmartContractServicegetBySolidityIDCall

  /// Synchronous. Unary.
  func getTxRecordByContractID(_ request: Proto_Query) throws -> Proto_Response
  /// Asynchronous. Unary.
  func getTxRecordByContractID(_ request: Proto_Query, completion: @escaping (Proto_Response?, CallResult) -> Void) throws -> Proto_SmartContractServicegetTxRecordByContractIDCall

}

internal final class Proto_SmartContractServiceServiceClient: ServiceClientBase, Proto_SmartContractServiceService {
  /// Synchronous. Unary.
  internal func createContract(_ request: Proto_Transaction) throws -> Proto_TransactionResponse {
    return try Proto_SmartContractServicecreateContractCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func createContract(_ request: Proto_Transaction, completion: @escaping (Proto_TransactionResponse?, CallResult) -> Void) throws -> Proto_SmartContractServicecreateContractCall {
    return try Proto_SmartContractServicecreateContractCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func updateContract(_ request: Proto_Transaction) throws -> Proto_TransactionResponse {
    return try Proto_SmartContractServiceupdateContractCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func updateContract(_ request: Proto_Transaction, completion: @escaping (Proto_TransactionResponse?, CallResult) -> Void) throws -> Proto_SmartContractServiceupdateContractCall {
    return try Proto_SmartContractServiceupdateContractCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func contractCallMethod(_ request: Proto_Transaction) throws -> Proto_TransactionResponse {
    return try Proto_SmartContractServicecontractCallMethodCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func contractCallMethod(_ request: Proto_Transaction, completion: @escaping (Proto_TransactionResponse?, CallResult) -> Void) throws -> Proto_SmartContractServicecontractCallMethodCall {
    return try Proto_SmartContractServicecontractCallMethodCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func getContractInfo(_ request: Proto_Query) throws -> Proto_Response {
    return try Proto_SmartContractServicegetContractInfoCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func getContractInfo(_ request: Proto_Query, completion: @escaping (Proto_Response?, CallResult) -> Void) throws -> Proto_SmartContractServicegetContractInfoCall {
    return try Proto_SmartContractServicegetContractInfoCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func contractCallLocalMethod(_ request: Proto_Query) throws -> Proto_Response {
    return try Proto_SmartContractServicecontractCallLocalMethodCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func contractCallLocalMethod(_ request: Proto_Query, completion: @escaping (Proto_Response?, CallResult) -> Void) throws -> Proto_SmartContractServicecontractCallLocalMethodCall {
    return try Proto_SmartContractServicecontractCallLocalMethodCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func contractGetBytecode(_ request: Proto_Query) throws -> Proto_Response {
    return try Proto_SmartContractServiceContractGetBytecodeCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func contractGetBytecode(_ request: Proto_Query, completion: @escaping (Proto_Response?, CallResult) -> Void) throws -> Proto_SmartContractServiceContractGetBytecodeCall {
    return try Proto_SmartContractServiceContractGetBytecodeCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func getBySolidityID(_ request: Proto_Query) throws -> Proto_Response {
    return try Proto_SmartContractServicegetBySolidityIDCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func getBySolidityID(_ request: Proto_Query, completion: @escaping (Proto_Response?, CallResult) -> Void) throws -> Proto_SmartContractServicegetBySolidityIDCall {
    return try Proto_SmartContractServicegetBySolidityIDCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func getTxRecordByContractID(_ request: Proto_Query) throws -> Proto_Response {
    return try Proto_SmartContractServicegetTxRecordByContractIDCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func getTxRecordByContractID(_ request: Proto_Query, completion: @escaping (Proto_Response?, CallResult) -> Void) throws -> Proto_SmartContractServicegetTxRecordByContractIDCall {
    return try Proto_SmartContractServicegetTxRecordByContractIDCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Proto_SmartContractServiceProvider {
  func createContract(request: Proto_Transaction, session: Proto_SmartContractServicecreateContractSession) throws -> Proto_TransactionResponse
  func updateContract(request: Proto_Transaction, session: Proto_SmartContractServiceupdateContractSession) throws -> Proto_TransactionResponse
  func contractCallMethod(request: Proto_Transaction, session: Proto_SmartContractServicecontractCallMethodSession) throws -> Proto_TransactionResponse
  func getContractInfo(request: Proto_Query, session: Proto_SmartContractServicegetContractInfoSession) throws -> Proto_Response
  func contractCallLocalMethod(request: Proto_Query, session: Proto_SmartContractServicecontractCallLocalMethodSession) throws -> Proto_Response
  func contractGetBytecode(request: Proto_Query, session: Proto_SmartContractServiceContractGetBytecodeSession) throws -> Proto_Response
  func getBySolidityID(request: Proto_Query, session: Proto_SmartContractServicegetBySolidityIDSession) throws -> Proto_Response
  func getTxRecordByContractID(request: Proto_Query, session: Proto_SmartContractServicegetTxRecordByContractIDSession) throws -> Proto_Response
}

internal protocol Proto_SmartContractServicecreateContractSession: ServerSessionUnary {}

fileprivate final class Proto_SmartContractServicecreateContractSessionBase: ServerSessionUnaryBase<Proto_Transaction, Proto_TransactionResponse>, Proto_SmartContractServicecreateContractSession {}

internal protocol Proto_SmartContractServiceupdateContractSession: ServerSessionUnary {}

fileprivate final class Proto_SmartContractServiceupdateContractSessionBase: ServerSessionUnaryBase<Proto_Transaction, Proto_TransactionResponse>, Proto_SmartContractServiceupdateContractSession {}

internal protocol Proto_SmartContractServicecontractCallMethodSession: ServerSessionUnary {}

fileprivate final class Proto_SmartContractServicecontractCallMethodSessionBase: ServerSessionUnaryBase<Proto_Transaction, Proto_TransactionResponse>, Proto_SmartContractServicecontractCallMethodSession {}

internal protocol Proto_SmartContractServicegetContractInfoSession: ServerSessionUnary {}

fileprivate final class Proto_SmartContractServicegetContractInfoSessionBase: ServerSessionUnaryBase<Proto_Query, Proto_Response>, Proto_SmartContractServicegetContractInfoSession {}

internal protocol Proto_SmartContractServicecontractCallLocalMethodSession: ServerSessionUnary {}

fileprivate final class Proto_SmartContractServicecontractCallLocalMethodSessionBase: ServerSessionUnaryBase<Proto_Query, Proto_Response>, Proto_SmartContractServicecontractCallLocalMethodSession {}

internal protocol Proto_SmartContractServiceContractGetBytecodeSession: ServerSessionUnary {}

fileprivate final class Proto_SmartContractServiceContractGetBytecodeSessionBase: ServerSessionUnaryBase<Proto_Query, Proto_Response>, Proto_SmartContractServiceContractGetBytecodeSession {}

internal protocol Proto_SmartContractServicegetBySolidityIDSession: ServerSessionUnary {}

fileprivate final class Proto_SmartContractServicegetBySolidityIDSessionBase: ServerSessionUnaryBase<Proto_Query, Proto_Response>, Proto_SmartContractServicegetBySolidityIDSession {}

internal protocol Proto_SmartContractServicegetTxRecordByContractIDSession: ServerSessionUnary {}

fileprivate final class Proto_SmartContractServicegetTxRecordByContractIDSessionBase: ServerSessionUnaryBase<Proto_Query, Proto_Response>, Proto_SmartContractServicegetTxRecordByContractIDSession {}


/// Main server for generated service
internal final class Proto_SmartContractServiceServer: ServiceServer {
  private let provider: Proto_SmartContractServiceProvider

  internal init(address: String, provider: Proto_SmartContractServiceProvider) {
    self.provider = provider
    super.init(address: address)
  }

  internal init?(address: String, certificateURL: URL, keyURL: URL, provider: Proto_SmartContractServiceProvider) {
    self.provider = provider
    super.init(address: address, certificateURL: certificateURL, keyURL: keyURL)
  }

  internal init?(address: String, certificateString: String, keyString: String, provider: Proto_SmartContractServiceProvider) {
    self.provider = provider
    super.init(address: address, certificateString: certificateString, keyString: keyString)
  }

  /// Start the server.
  internal override func handleMethod(_ method: String, handler: Handler, queue: DispatchQueue) throws -> Bool {
    let provider = self.provider
    switch method {
    case "/proto.SmartContractService/createContract":
      try Proto_SmartContractServicecreateContractSessionBase(
        handler: handler,
        providerBlock: { try provider.createContract(request: $0, session: $1 as! Proto_SmartContractServicecreateContractSessionBase) })
          .run(queue: queue)
      return true
    case "/proto.SmartContractService/updateContract":
      try Proto_SmartContractServiceupdateContractSessionBase(
        handler: handler,
        providerBlock: { try provider.updateContract(request: $0, session: $1 as! Proto_SmartContractServiceupdateContractSessionBase) })
          .run(queue: queue)
      return true
    case "/proto.SmartContractService/contractCallMethod":
      try Proto_SmartContractServicecontractCallMethodSessionBase(
        handler: handler,
        providerBlock: { try provider.contractCallMethod(request: $0, session: $1 as! Proto_SmartContractServicecontractCallMethodSessionBase) })
          .run(queue: queue)
      return true
    case "/proto.SmartContractService/getContractInfo":
      try Proto_SmartContractServicegetContractInfoSessionBase(
        handler: handler,
        providerBlock: { try provider.getContractInfo(request: $0, session: $1 as! Proto_SmartContractServicegetContractInfoSessionBase) })
          .run(queue: queue)
      return true
    case "/proto.SmartContractService/contractCallLocalMethod":
      try Proto_SmartContractServicecontractCallLocalMethodSessionBase(
        handler: handler,
        providerBlock: { try provider.contractCallLocalMethod(request: $0, session: $1 as! Proto_SmartContractServicecontractCallLocalMethodSessionBase) })
          .run(queue: queue)
      return true
    case "/proto.SmartContractService/ContractGetBytecode":
      try Proto_SmartContractServiceContractGetBytecodeSessionBase(
        handler: handler,
        providerBlock: { try provider.contractGetBytecode(request: $0, session: $1 as! Proto_SmartContractServiceContractGetBytecodeSessionBase) })
          .run(queue: queue)
      return true
    case "/proto.SmartContractService/getBySolidityID":
      try Proto_SmartContractServicegetBySolidityIDSessionBase(
        handler: handler,
        providerBlock: { try provider.getBySolidityID(request: $0, session: $1 as! Proto_SmartContractServicegetBySolidityIDSessionBase) })
          .run(queue: queue)
      return true
    case "/proto.SmartContractService/getTxRecordByContractID":
      try Proto_SmartContractServicegetTxRecordByContractIDSessionBase(
        handler: handler,
        providerBlock: { try provider.getTxRecordByContractID(request: $0, session: $1 as! Proto_SmartContractServicegetTxRecordByContractIDSessionBase) })
          .run(queue: queue)
      return true
    default:
      return false
    }
  }
}

